### ISSUE TITLE
utils.getIncludedRecords() should return always an array

### ISSUE THREAD

**Issue by germanp** [mrichar1/pinia-jsonapi#7]
It should return an empty array to be consistent with the data type, it returns empty object wich is not quite useful.

https://github.com/mrichar1/pinia-jsonapi/blob/666e9345f4d3af6d4427e3f5eb5725a4848ea60a/src/lib.js#L520

**Comment by mrichar1** [comment]
Thanks for flagging this up - yes it was inconsistent and I've changed as suggested :+1:
